<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="471" started-at="2015-05-11T21:50:55Z" finished-at="2015-05-11T21:50:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="471" started-at="2015-05-11T21:50:55Z" finished-at="2015-05-11T21:50:55Z">
      <class name="Testing.NewTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Testing.NewTest@6dea9b6e]" name="setUp" is-config="true" duration-ms="38" started-at="2015-05-11T14:50:55Z" finished-at="2015-05-11T14:50:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getusertest()[pri:0, instance:Testing.NewTest@6dea9b6e]" name="getusertest" duration-ms="291" started-at="2015-05-11T14:50:55Z" finished-at="2015-05-11T14:50:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [a@yahoo.com[ but found ]null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [a@yahoo.com[ but found ]null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at Testing.NewTest.getusertest(NewTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getusertest -->
        <test-method status="PASS" signature="saveusertest()[pri:0, instance:Testing.NewTest@6dea9b6e]" name="saveusertest" duration-ms="127" started-at="2015-05-11T14:50:55Z" finished-at="2015-05-11T14:50:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveusertest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Testing.NewTest@6dea9b6e]" name="tearDown" is-config="true" duration-ms="0" started-at="2015-05-11T14:50:55Z" finished-at="2015-05-11T14:50:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Testing.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
